### ISSUE TITLE
Kinematic Plasticity Test Run

### ISSUE THREAD

**Issue by crswong888** [albiedahal/otter#1]
@albiedahal I am committing some files that contain the various results from HPC Falcon cluster. I ran two jobs: one for `cantilever_plastic.i` and another for `cantilever_plastic_refactor.i`. Both files were executed exactly how they are at `HEAD` using 16 cores each and both, ultimately, failed to converge. The former ran for approximately ~8 hours and the latter for ~1 hour.

Here's what you'll find in `kinematic_tests/falcon1_outputs/`:
- `*_out` contain the terminal printouts. They are timestamped on the first and last lines.
- `*.eXXXXXXX` contain any error messages that were printed.
- `*.e` and `*.csv` are the standard output files.

**Comment by crswong888** [comment]
@albiedahal GitHub won't let me upload `cantilever_plastic_out.e`, because it is too large, so I ommitted that file. If you want to see that file I uploaded the whole directory to `[our box](https://unh.box.com/s/s0wfgi2nua4463t3qjn6ykhmo2i0pcch) as well.

**Comment by albiedahal** [comment]
@crswong888 Got the files. Thanks a bunch!

**Comment by crswong888** [comment]
I will close this then. Let me know if there's anything else you need.
